### ISSUE TITLE
Xoshiro256PlusRandom.cs use xoshiro256** too ?

### ISSUE THREAD

**Issue by achan001** [colgreen/Redzen#1]
https://github.com/colgreen/Redzen/blob/master/Redzen/Random/Xoshiro256PlusRandom.cs

Why NextBytes () uses both xoshiro256+ and xoshiro256** ? 

> ulong result = RotateLeft(s1 * 5, 7) * 9;

**Comment by colgreen** [comment]
Fixed. Thanks for the feedback.
