### ISSUE TITLE
ZigguratGaussian - always returns mean

### ISSUE THREAD

**Issue by studentutu** [colgreen/Redzen#19]
No matter which type of distribution of the ZigguratGaussian function used - it always returns mean
I tried to use older releases - the same thing.
Are you sure, this will work on Xamarin - IOS/Android/ other devices?

**Comment by colgreen** [comment]
Hi @studentutu. To help understand the problem could you please post some example code that demonstrates the problem.

Thanks.

**Comment by studentutu** [comment]
sorry incorrectly used the Random.Int where we would need to use Random.Long. Works as expected
