### ISSUE TITLE
EnumerableUtils.RangeRandomOrder performance improvement

### ISSUE THREAD

**Issue by ShadowGlass0** [colgreen/Redzen#2]
A small performance improvement to the above: There's no need to store the returned value back into the array. That value will not be used again:

```                   int tmp = arr[swapIdx];
                   arr[swapIdx] = arr[i];
 -                 arr[i] = tmp;
   
 -                 yield return arr[i];
 +                 yield return tmp;
               }
```

**Comment by colgreen** [comment]
Thanks for this. I have made the change and it will be in a nuget release shortly.
